// Response | GET : https://v1.formula-1.api-sports.io/rankings/races?race=1273
export const race = [
  {
    race: {
      id: 1273,
    },
    driver: {
      id: 20,
      name: 'Lewis Hamilton',
      abbr: 'HAM',
      number: 44,
      image: 'https://media.api-sports.io/formula-1/drivers/20.png',
    },
    team: {
      id: 5,
      name: 'Mercedes-AMG Petronas',
      logo: 'https://media.api-sports.io/formula-1/teams/5.png',
    },
    position: 1,
    time: '1:32:03.897',
    laps: 56,
    grid: '2',
    pits: 2,
    gap: null,
  },
  {
    race: {
      id: 1273,
    },
    driver: {
      id: 25,
      name: 'Max Verstappen',
      abbr: 'VER',
      number: 1,
      image: 'https://media.api-sports.io/formula-1/drivers/25.png',
    },
    team: {
      id: 1,
      name: 'Red Bull Racing',
      logo: 'https://media.api-sports.io/formula-1/teams/1.png',
    },
    position: 2,
    time: '+0.745',
    laps: 56,
    grid: '1',
    pits: 2,
    gap: null,
  },
  {
    race: {
      id: 1273,
    },
    driver: {
      id: 5,
      name: 'Valtteri Bottas',
      abbr: 'BOT',
      number: 77,
      image: 'https://media.api-sports.io/formula-1/drivers/5.png',
    },
    team: {
      id: 5,
      name: 'Mercedes-AMG Petronas',
      logo: 'https://media.api-sports.io/formula-1/teams/5.png',
    },
    position: 3,
    time: '+37.383',
    laps: 56,
    grid: '3',
    pits: 3,
    gap: null,
  },
  {
    race: {
      id: 1273,
    },
    driver: {
      id: 49,
      name: 'Lando Norris',
      abbr: 'NOR',
      number: 4,
      image: 'https://media.api-sports.io/formula-1/drivers/49.png',
    },
    team: {
      id: 2,
      name: 'McLaren Racing',
      logo: 'https://media.api-sports.io/formula-1/teams/2.png',
    },
    position: 4,
    time: '+46.466',
    laps: 56,
    grid: '7',
    pits: 2,
    gap: null,
  },
  {
    race: {
      id: 1273,
    },
    driver: {
      id: 10,
      name: 'Sergio Perez',
      abbr: 'PER',
      number: 11,
      image: 'https://media.api-sports.io/formula-1/drivers/10.png',
    },
    team: {
      id: 1,
      name: 'Red Bull Racing',
      logo: 'https://media.api-sports.io/formula-1/teams/1.png',
    },
    position: 5,
    time: '+52.047',
    laps: 56,
    grid: '11',
    pits: 3,
    gap: null,
  },
  {
    race: {
      id: 1273,
    },
    driver: {
      id: 34,
      name: 'Charles Leclerc',
      abbr: 'LEC',
      number: 16,
      image: 'https://media.api-sports.io/formula-1/drivers/34.png',
    },
    team: {
      id: 3,
      name: 'Scuderia Ferrari',
      logo: 'https://media.api-sports.io/formula-1/teams/3.png',
    },
    position: 6,
    time: '+59.090',
    laps: 56,
    grid: '4',
    pits: 2,
    gap: null,
  },
  {
    race: {
      id: 1273,
    },
    driver: {
      id: 14,
      name: 'Daniel Ricciardo',
      abbr: 'RIC',
      number: 3,
      image: 'https://media.api-sports.io/formula-1/drivers/14.png',
    },
    team: {
      id: 2,
      name: 'McLaren Racing',
      logo: 'https://media.api-sports.io/formula-1/teams/2.png',
    },
    position: 7,
    time: '+1:06.004',
    laps: 56,
    grid: '6',
    pits: 2,
    gap: null,
  },
  {
    race: {
      id: 1273,
    },
    driver: {
      id: 24,
      name: 'Carlos Sainz Jr',
      abbr: 'SAI',
      number: 55,
      image: 'https://media.api-sports.io/formula-1/drivers/24.png',
    },
    team: {
      id: 3,
      name: 'Scuderia Ferrari',
      logo: 'https://media.api-sports.io/formula-1/teams/3.png',
    },
    position: 8,
    time: '+1:07.100',
    laps: 56,
    grid: '8',
    pits: 2,
    gap: null,
  },
  {
    race: {
      id: 1273,
    },
    driver: {
      id: 82,
      name: 'Yuki Tsunoda',
      abbr: 'TSU',
      number: 22,
      image: 'https://media.api-sports.io/formula-1/drivers/82.png',
    },
    team: {
      id: 7,
      name: 'Scuderia AlphaTauri Honda',
      logo: 'https://media.api-sports.io/formula-1/teams/7.png',
    },
    position: 9,
    time: '+1:25.692',
    laps: 56,
    grid: '13',
    pits: 2,
    gap: null,
  },
  {
    race: {
      id: 1273,
    },
    driver: {
      id: 31,
      name: 'Lance Stroll',
      abbr: 'STR',
      number: 18,
      image: 'https://media.api-sports.io/formula-1/drivers/31.png',
    },
    team: {
      id: 17,
      name: 'Aston Martin F1 Team',
      logo: 'https://media.api-sports.io/formula-1/teams/17.png',
    },
    position: 10,
    time: '+1:26.713',
    laps: 56,
    grid: '10',
    pits: 2,
    gap: null,
  },
  {
    race: {
      id: 1273,
    },
    driver: {
      id: 7,
      name: 'Kimi Raikkonen',
      abbr: 'RAI',
      number: 7,
      image: 'https://media.api-sports.io/formula-1/drivers/7.png',
    },
    team: {
      id: 18,
      name: 'Alfa Romeo',
      logo: 'https://media.api-sports.io/formula-1/teams/18.png',
    },
    position: 11,
    time: '+1:28.864',
    laps: 56,
    grid: '14',
    pits: 2,
    gap: null,
  },
  {
    race: {
      id: 1273,
    },
    driver: {
      id: 29,
      name: 'Antonio Giovinazzi',
      abbr: 'GIO',
      number: 99,
      image: 'https://media.api-sports.io/formula-1/drivers/29.png',
    },
    team: {
      id: 18,
      name: 'Alfa Romeo',
      logo: 'https://media.api-sports.io/formula-1/teams/18.png',
    },
    position: 12,
    time: '1 Lap',
    laps: 55,
    grid: '12',
    pits: 2,
    gap: null,
  },
  {
    race: {
      id: 1273,
    },
    driver: {
      id: 28,
      name: 'Esteban Ocon',
      abbr: 'OCO',
      number: 31,
      image: 'https://media.api-sports.io/formula-1/drivers/28.png',
    },
    team: {
      id: 13,
      name: 'Alpine F1 Team',
      logo: 'https://media.api-sports.io/formula-1/teams/13.png',
    },
    position: 13,
    time: '1 Lap',
    laps: 55,
    grid: '16',
    pits: 2,
    gap: null,
  },
  {
    race: {
      id: 1273,
    },
    driver: {
      id: 51,
      name: 'George Russell',
      abbr: 'RUS',
      number: 63,
      image: 'https://media.api-sports.io/formula-1/drivers/51.png',
    },
    team: {
      id: 12,
      name: 'Williams F1 Team',
      logo: 'https://media.api-sports.io/formula-1/teams/12.png',
    },
    position: 14,
    time: '1 Lap',
    laps: 55,
    grid: '15',
    pits: 2,
    gap: null,
  },
  {
    race: {
      id: 1273,
    },
    driver: {
      id: 19,
      name: 'Sebastian Vettel',
      abbr: 'VET',
      number: 5,
      image: 'https://media.api-sports.io/formula-1/drivers/19.png',
    },
    team: {
      id: 17,
      name: 'Aston Martin F1 Team',
      logo: 'https://media.api-sports.io/formula-1/teams/17.png',
    },
    position: 15,
    time: '1 Lap',
    laps: 55,
    grid: '20',
    pits: 1,
    gap: null,
  },
  {
    race: {
      id: 1273,
    },
    driver: {
      id: 80,
      name: 'Mick Schumacher',
      abbr: 'MSC',
      number: 47,
      image: 'https://media.api-sports.io/formula-1/drivers/80.png',
    },
    team: {
      id: 14,
      name: 'Haas F1 Team',
      logo: 'https://media.api-sports.io/formula-1/teams/14.png',
    },
    position: 16,
    time: '1 Lap',
    laps: 55,
    grid: '18',
    pits: 2,
    gap: null,
  },
  {
    race: {
      id: 1273,
    },
    driver: {
      id: 36,
      name: 'Pierre Gasly',
      abbr: 'GAS',
      number: 10,
      image: 'https://media.api-sports.io/formula-1/drivers/36.png',
    },
    team: {
      id: 7,
      name: 'Scuderia AlphaTauri Honda',
      logo: 'https://media.api-sports.io/formula-1/teams/7.png',
    },
    position: 17,
    time: null,
    laps: 52,
    grid: '5',
    pits: 4,
    gap: null,
  },
  {
    race: {
      id: 1273,
    },
    driver: {
      id: 61,
      name: 'Nicholas Latifi',
      abbr: 'LAT',
      number: 6,
      image: 'https://media.api-sports.io/formula-1/drivers/61.png',
    },
    team: {
      id: 12,
      name: 'Williams F1 Team',
      logo: 'https://media.api-sports.io/formula-1/teams/12.png',
    },
    position: 18,
    time: null,
    laps: 51,
    grid: '17',
    pits: 3,
    gap: null,
  },
  {
    race: {
      id: 1273,
    },
    driver: {
      id: 4,
      name: 'Fernando Alonso',
      abbr: 'ALO',
      number: 14,
      image: 'https://media.api-sports.io/formula-1/drivers/4.png',
    },
    team: {
      id: 13,
      name: 'Alpine F1 Team',
      logo: 'https://media.api-sports.io/formula-1/teams/13.png',
    },
    position: 19,
    time: 'DNF',
    laps: 32,
    grid: '9',
    pits: 3,
    gap: null,
  },
  {
    race: {
      id: 1273,
    },
    driver: {
      id: 81,
      name: 'Nikita Mazepin',
      abbr: 'MAZ',
      number: 9,
      image: 'https://media.api-sports.io/formula-1/drivers/81.png',
    },
    team: {
      id: 14,
      name: 'Haas F1 Team',
      logo: 'https://media.api-sports.io/formula-1/teams/14.png',
    },
    position: 20,
    time: 'DNF',
    laps: 0,
    grid: '19',
    pits: 0,
    gap: null,
  },
]
