export const DRIVER_TO_ROW = {
  'Charles Leclerc': 11,
  'Carlos Sainz Jr': 10,
  'Lewis Hamilton': 17,
  'George Russell': 16,
  'Kevin Magnussen': 12,
  'Valtteri Bottas': 3,
  'Esteban Ocon': 6,
  'Yuki Tsunoda': 5,
  'Fernando Alonso': 7,
  'Guanyu Zhou': 2,
  'Mick Schumacher': 13,
  'Lance Stroll': 8,
  'Alexander Albon': 20,
  'Daniel Ricciardo': 14,
  'Lando Norris': 15,
  'Nicholas Latifi': 21,
  'Sebastian Vettel': 9,
  'Sergio Perez': 19,
  'Max Verstappen': 18,
  'Pierre Gasly': 4,
}
