name: "Ping database"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * THU"

jobs:
  ping-database:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Ping database so Supabase doesn't shut down
        run: |
          yarn
          node revalidate.js
