name: "Revalidate pages"
on:
  workflow_dispatch:
  schedule:
  # - cron: "0 10 * * THU"
  - cron: "0 10 * * MON,THU"

jobs:
  revalidate-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Revalidate pages so Supabase doesn't shut down
        env:
          REVALIDATE_TOKEN: ${{ secrets.REVALIDATE_TOKEN }}
          SEASON: 2023
        run: |
          yarn
          node revalidate.js "$REVALIDATE_TOKEN" "$SEASON"
