name: "Update Website Data"
on:
  workflow_dispatch:
  schedule:
    # - cron: "0 10 * * MON"

jobs:
  update-website-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - name: Update website data from fastf1 python package
        env:
          REVALIDATE_TOKEN: ${{ secrets.REVALIDATE_TOKEN }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          SEASON: 2024
        run: |
          pip install -r supabase-data-generator/requirements.txt
          python supabase-data-generator/generate-data.py
